version: "3.9"
services:
  api:
    container_name: 'api-mercado-livre'
    image: node:14.17.0-alpine
    working_dir: /usr/src/mercado-livre
    volumes:
      - .:/usr/src/mercado-livre/
    restart: always
    command: yarn dev:server
    env_file: .env.dev
    ports:
      - "3333:3333"
